<template>
  <div class="containerComponenteFaq">
    <div v-for="(pregunta,idx) in preguntas" :key="idx" class="faqItem" data-aos="fade-in" data-aos-delay="300">
      <b-button v-b-toggle="pregunta.id" block class="btnFaq">
        {{ pregunta.titulo }} - <b-icon-arrow-bar-down />
      </b-button>
      <b-collapse :id="pregunta.id" :key="idx" class="mt-2">
        <b-card>
          <p class="cardFaq" v-html="pregunta.texto" />
        </b-card>
      </b-collapse>
    </div>
  </div>
</template>

<script>
export default {
  name: 'Faq',
  data () {
    return {
      preguntas: [
        { id: '1', titulo: 'Realment hi ha diferència entre un aliment ecològic i un que no ho és?', texto: 'I tant,  encara que de vegades no es pugui apreciar a simple vista. Podem dir que hi ha dues diferències clares: la manera en que s’ha produït i la qualitat pròpia  del aliment. L’aliment ecològic és produeix amb el mínim d’impacte ambiental. No es fan servir plaguicides, herbicides ni adobs minerals de síntesi. La contaminació del medi que es dona de manera sistemàtica  a l’agricultura industrialitzada convencional no succeeix amb la pràctica de l’agricultura ecològica. Per tant, encara que poder no es vegi, darrera d’un aliment ecològic hi ha la preservació del medi ambient. Sobre la qualitat del producte ecològic hi ha una característica  que tampoc s’aprecia a simple vista però que és molt important: la manca de residus de plaguicides químics de síntesi. Sols aquest fet li dóna una garantia de salut a l’aliment ecològic que no té l’aliment convencional. A més diversos estudis han demostrat que la qualitat nutricional de l’aliment ecològic és major. Això, en bona part, s’explica perquè l’aliment ecològic s’ha conreat sense forçar e intensificar la seva producció, deixant que el cultiu es desenvolupi més al seu ritme sobre un sòl fèrtil i viu. ' },
        { id: '2', titulo: 'Qualsevol producte alimentari es pot obtenir de manera ecològica?', texto: 'La majoria d’aliments tenen desenvolupada una normativa que especifica en quines condicions s’han de produir i elaborar els aliments ecològics. Així podem trobar qualsevol fruita i verdura fresca i transformada, carns, ous, llets i qualsevol altre producció animal, mel, vins, oli, fruits secs, plats precuinats, congelats, etc., tot de producció ecològica.  Si que es cert que pot haver cert tipus d’aliments que sigui més difícils d’obtenir i que per tant estiguin poc presents al mercat. Esperem que la ja de per si extensa oferta d’aliments ecològics sigui cada cop més àmplia i accessible.' },
        { id: '3', titulo: 'Quina diferència hi ha entre un producte en conversió', texto: 'Un pagès que decideixi començar a fer agricultura ecològica haurà de convertir la seva manera de conrear. Al posar-se en contacte amb l’entitat certificadora aquesta verificarà que les seves terres s’adapten als requisits per fer producció ecològica i s’inicia un procés que s’anomena de conversió a l’agricultura ecològica. Aquest procés es variable segons el tipus de cultiu però té una durada mínima de 2 anys. Durant el primer any, que les certificadores anomenen “any 0”, el pagès farà agricultura ecològica però no podrà vendre els seus productes com a tal. L’objectiu d’aquesta mesura es preserva la qualitat davant el possible risc de que hi hagin residus de plaguicides no ecològics al sòl que puguin anar a parar al producte. Passat aquest primer any el producte te el segell de “conversió a l’agricultura ecològica”. El fet de tenir un segell de reconeixement permet al pagès poder intentar col·locar els seus productes al mercat ecològic. Passat el període de conversió (1 any en el cas de cultius herbacis i 2 en arbres) el producte ja tindrà el segell ecològic i es podrà vendre com a tal.' },
        { id: '4', titulo: 'Els aliments ecològics només es poden vendre a certes botigues?', texto: 'No hi ha restricció als tipus de comerços que poden vendre productes ecològics. El CCPAE si que dona l’opció a aquells comerços que vulguin diferenciar-se de inscriure’s a un registre de Establiments Minoristes Recomanats. El CCPAE fa uns controls sobre aquest establiments i edita una Guia Directori on apareixen relacionats.  A la web del <a href="http://www.ccpae.org" target="_blank">CCPAE</a> trobareu informació sobre com ser una Botiga Recomanada.' },
        { id: '5', titulo: 'Puc trobar aliments ecològics als restaurants?', texto: 'Si, dependrà del restaurant. En principi els establiments que utilitzen en la preparació dels seus menús algun aliment ecològic ja s’encarreguen de fer-ho constar a les seves cartes. No existeix, però, un registre de Restaurants Recomanats, com passa amb les botigues.' },
        { id: '6', titulo: 'Que haig de fer per produir aliments ecològics?', texto: 'El primer que cal es informació. A internet podeu trobar molta. Per algú que tingui un plantejament professional, un bon punt de partida pot ser  el <a href="http://agricultura.gencat.cat/ca/inici/" target="_blank">Portal de la PAE del Departament d’Agricultura de la Generalitat de Catalunya</a> . Allà trobareu informació general, sobre normativa, sobre el CCPAE. sobre ajuts a la producció, etc. Es important que us atureu a revisar amb atenció la normativa ja que allà s’especifiquen les pràctiques i tècniques,  els adobs i els mètodes i estratègies de control de plagues i malalties que es poden implementar. Aquestes qüestions sovint són les que més amoïnen als productors que volen convertir la seva producció.La formació és moltes vegades una necessitat pels que volen començar a fer agricultura ecològica. Cada cop són més freqüents els cursos de formació sobre aquest tipus d’agricultura. En podem trobar de més generals i de més específics i tècnics. Son moltes i diverses les entitats que els organitzen. Les escoles de capacitació agrària del Departament d’Agricultura programen amb freqüència cursos orientat al sector més professional . <a href="http://agricultura.gencat.cat/ca/ambits/agricultura/dar_bones_practiques_agraries/" target="_blank">L’Escola Agrària de Manresa </a>, destaca dintre d’aquestes per ser una pionera en aquest àmbit a Catalunya. L’ERA (Espai de Recursos Agroecològics, <a href="https://associaciolera.org/" target="_blank">www.associaciolera.org</a> ) es una entitat nascuda en l’àmbit d’aquesta escola que fa temps que treballa en la dinamització del sector organitzant jornades i activitats formatives. Els llibres són també una bona e imprescindible font de coneixement sobre la manera de produir aliments ecològics. L’oferta és amplia però per qui vulgui iniciar-se o aprofundir en qüestions més tècniques, el llibre <b>“CONOCIMIENTOS, TECNICAS I PRODUCTOS PARA LA AGRICULTURA Y LA GANADERIA ECOLÓGICA“ </b>es lectura recomanada. L’edita Joana Labrador , actual presidenta de la SEAE (Sociedad Española de Agricultura Ecológica, <a href="https://www.agroecologia.net/" target="_blank">www.agroecologia.net</a> ). Un cop decidits a produir no hem de trigar en posar-nos en contacte amb el CCPAE <a href="http://www.ccpae.org/" target="_blank">(www.ccpae.org)</a>  per poder iniciar quan abans millor el procés de conversió capa l’agricultura ecològica.' },
        { id: '7', titulo: 'Qui em pot assessorar per començar produir en ecològic?', texto: 'Qui em pot assessorar per començar produir en ecològic? Pot haver dues necessitats d’assessorament: sobre la producció i sobre la comercialització. En tots dos àmbits l’oferta d’assessorament es encara una mica difusa. En quan a producció vegetal hi ha al territori algunes ADV, que com la nostra, donen servei d’assessorament en producció ecològica. Son poques i menys encara les que agrupen exclusivament a productors ecològics. Es cert, però, que augmenta el número d’ADV que es preocupen per donar un bon servei  d’assessorament als productors que s’inicien o ja produeixen en ecològic. Al marge d’aquestes agrupacions, entitats com l’ERA (<a href="https://associaciolera.org/" target="_blank">www.associaciolera.org</a> ) poden prestar assessorament de manera directa o indirecta.' },
        { id: '8', titulo: 'On puc trobar llavors ecològiques i productes fitosanitaris que es puguin utilitzar en Agricultura Ecològica?', texto: 'Sobre les llavors, a la mateixa base de dades de disponibilitat de llavors biològiques del Ministerio que abans em citat, el poden consultar les adreces i telèfons dels proveïdors. Us podeu posar en contacte amb ells i us donaran informació sobre con distribueixen les llavors. En quan als fitosanitaris, alguns son fàcils de trobar (sals de coure, sofres, olis minerals, bt,….) i altres no tant. A botigues on es venen fitosanitaris convencionals que estiguin ben sortides es fàcil trobar apartats específics amb per l’Agricultura Ecològica. Si no,  la recerca per Internet acostuma a donar bons resultats en la recerca i l’adquisició de productes fitosanitaris utilitzables en la producció ecològica' },
        { id: '9', titulo: 'Per abonar la terra: puc fer servir qualsevol tipus de fem o residu orgànic? Puc fer servir adobs minerals?', texto: 'Mantenir un terra viu i fèrtil es la base de l’agricultura ecològica. L’aport de matèria orgànica es imprescindible per assolir aquest objectiu. Els fems i el compost són els materials més àmpliament aplicats. La procedència dels fems ha de ser preferentment de ramaderia ecològica. La poca disponibilitat obliga sovint a haver de fer servir fems de ramaderia convencional no intensiva que compleixin uns requisits. A la pràctica no es possible fer servir ni gallinassa provinent de granges de gallines ponedores en bateria ni fems de conills ja que es tracta de bestiar que esta engabiat i no toca a terra . En qualsevol cas, només es podran fer servir si prèviament  es fan compostar un mínim de 6 mesos. El compost si es pot fer a la mateixa finca millor. Al mercat hi ha molts compost i adobs orgànics comercials elaborats amb materials d’origen vegetal i/o animal. Uns quants ja estan orientats al mercat de productors ecològics i venen avalats per entitats certificadores reconegudes. Hi ha també al mercat una àmplia gama de fertilitzants líquids utilitzables en agricultura ecològica.  Sempre es convenient abans d’adquirir un fertilitzant comercial demanar al CCPAE si es pot utilitzar sense restriccions. No cal oblidar l’adob en verd, una pràctica bàsica en el manteniment i la millora de la fertilitat del sòl en agricultura ecològica. Sobre els adobs minerals els que són d’origen natural (sulfats de potassa i magnesi, etc.) si que es poden fer servir. L’objectiu de la seva aplicació ha de ser fonamentalment la correcció de carències del sòl.' },
        { id: '10', titulo: 'Tots els aliments ecològics tenen un distintiu que els identifica com a tal?', texto: 'A l’etiqueta dels envasos d’aliments ecològics ha d’aparèixer el segell de l’entitat que el certifica com a ecològic. Em de tenir molt clar que, cap aliment es pot anomenar o publicitar com a ecològic si no està certificat i disposa del segell corresponent. Es dona el cas d’etiquetes de productes que per motius de mercat o tenen segells de varies certificadores. Ha de quedar clar que que tingui més segells no vol dir que sigui més ecològic. Això si com a mínim ha de tenir un de vàlid. A la web del CCPAE (www.ccpae.org) podeu els diferents tipus de segells que podeu trobar als productes ecològics i l’entitat certificadora que corresponent a cadascun.' },
        { id: '11', titulo: 'Quins productes fitosanitaris o tècniques puc fer servir per controlar plagues i malalties dels cultius en Agricultura Ecològica?', texto: 'A l’apartat  <a href="https://www.irta.es/ca/projecte/plagues-que-afecten-a-la-industria-agroalimentaria-control-biologic-i-deteccio-duna-especie-invasiva/" target="_blank">Plagues i malalties dels cultius i el seu control en Agricultura Ecològica</a> trobareu informació sobre aquesta qüestió.' },
        { id: '12', titulo: 'Quines llavors o planters puc fer servir en Agricultura Ecològica?', texto: 'Han de ser de producció ecològica. Les llavors i el planter que es puguem produir a la nostre finca evidentment es poden fer servir si ja estem fent agricultura ecològica. Si hem d’adquirir llavors hem de consultar una base de dades que hi ha a la web del Ministerio de Agricultura d’Espanya  on hi ha l’oferta de varietats disponibles  en producció ecològica al mercat espanyol. Si no trobem en aquesta base de dades una determinada varietat   que ens interessa per les seves característiques podem mirar d’aconseguir llavor convencional “sense tractar” d’aquesta. Important, cal sol·licitar al CCPAE l’ utilització d’aquest tipus de llavors. En cap cas es poden fer servir llavors convencionals tractades amb fitosanitaris. Sobre el planter d’hortícoles i d’aromàtiques i medicinals podeu consultar la Guia Directori del CCPAE <a href="http://www.ccpae.org" target="_blank">(www.ccpae.org)</a> per saber quins planteraires ofereixen planter ecològic certificat a Catalunya. Actualment, no hi ha oferta de planter d’arbres fruiters a Catalunya.' }
      ]
    }
  }
}
</script>

<style lang="scss" scoped>
